const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  getProjects: () => ipcRenderer.invoke('db:getProjects'),
  createProject: (data) => ipcRenderer.invoke('db:createProject', data),
  updateProject: (data) => ipcRenderer.invoke('db:updateProject', data),
  deleteProject: (id) => ipcRenderer.invoke('db:deleteProject', id),
  getTodos: (projectId) => ipcRenderer.invoke('db:getTodos', projectId),
  createTodo: (data) => ipcRenderer.invoke('db:createTodo', data),
  updateTodo: (data) => ipcRenderer.invoke('db:updateTodo', data),
  deleteTodo: (id) => ipcRenderer.invoke('db:deleteTodo', id),
  updateTodoStatus: (data) => ipcRenderer.invoke('db:updateTodoStatus', data),
  onShortcut: (callback) => ipcRenderer.on('shortcut', (_, shortcut) => callback(shortcut)),
  workStart: (projectId) => ipcRenderer.invoke('work:start', projectId),
  workStop: () => ipcRenderer.invoke('work:stop'),
  workGetProjectToday: (projectId) => ipcRenderer.invoke('work:getProjectToday', projectId),
  workGetProjectStats: (projectId) => ipcRenderer.invoke('work:getProjectStats', projectId),
  workGetToday: () => ipcRenderer.invoke('work:getToday'),
  workGetReport: () => ipcRenderer.invoke('work:getReport'),
  settingsGet: (key) => ipcRenderer.invoke('settings:get', key),
  settingsSet: (key, value) => ipcRenderer.invoke('settings:set', key, value),
  showNotification: (title, body) => ipcRenderer.invoke('notification:show', title, body),
  updateTrayState: (state) => ipcRenderer.invoke('tray:update', state),
  onTrayState: (callback) => ipcRenderer.on('tray:state', (_, state) => callback(state)),
  showBreakOverlay: () => ipcRenderer.invoke('break:show'),
  hideBreakOverlay: () => ipcRenderer.invoke('break:hide'),
  snoozeBreak: (minutes) => ipcRenderer.invoke('break:snooze', minutes),
  skipBreak: () => ipcRenderer.invoke('break:skip'),
  tagsGetAll: (projectId) => ipcRenderer.invoke('tags:getAll', projectId),
  tagsCreate: (data) => ipcRenderer.invoke('tags:create', data),
  tagsDelete: (id) => ipcRenderer.invoke('tags:delete', id),
  tagsAttach: (todoId, tagId) => ipcRenderer.invoke('tags:attach', todoId, tagId),
  tagsDetach: (todoId, tagId) => ipcRenderer.invoke('tags:detach', todoId, tagId),
  tagsGetByTodo: (todoId) => ipcRenderer.invoke('tags:getByTodo', todoId),
  subtasksGetByTodo: (todoId) => ipcRenderer.invoke('subtasks:getByTodo', todoId),
  subtasksCreate: (data) => ipcRenderer.invoke('subtasks:create', data),
  subtasksToggle: (id, completed) => ipcRenderer.invoke('subtasks:toggle', id, completed),
  subtasksDelete: (id) => ipcRenderer.invoke('subtasks:delete', id),
  subtasksReorder: (todoId, orderedIds) => ipcRenderer.invoke('subtasks:reorder', todoId, orderedIds),
  updateCheck: () => ipcRenderer.invoke('update:check'),
  updateDownload: () => ipcRenderer.invoke('update:download'),
  updateInstall: () => ipcRenderer.invoke('update:install'),
  onUpdateAvailable: (callback) => ipcRenderer.on('update-available', (_, info) => callback(info)),
  onUpdateProgress: (callback) => ipcRenderer.on('update-progress', (_, progress) => callback(progress)),
  onUpdateDownloaded: (callback) => ipcRenderer.on('update-downloaded', (_, info) => callback(info)),
  backupExport: () => ipcRenderer.invoke('backup:export'),
  backupImport: () => ipcRenderer.invoke('backup:import'),
});
